name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        py -m venv .venv 
        pip install pyinstaller tcod numpy

    - name: Build Windows Executable
      run: |
        .venv\bin\activate.bat
        pyinstaller -n coten -w --paths "map_gen:components:event_handlers" --add-data "dejavu10x10_gs_tc.png;." --add-data "menu_background.png;." main.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
